"""Paths and tunables for the gtm_kb pipeline.

Keeping these in one place means tests can point the index at a tmp dir and the
CLI/DoD paths stay stable.
"""

from __future__ import annotations

from pathlib import Path

# src/gtm_kb/config.py -> repo root is two parents up from the package dir.
PKG_DIR = Path(__file__).resolve().parent
REPO_DIR = PKG_DIR.parent.parent  # gtm-knowledge-base/

CORPUS_DIR = REPO_DIR / "data" / "northstar"

# The five category folders that hold the 30 corpus docs. The data README lives
# at data/northstar/README.md and is intentionally NOT one of the 30 (it's meta).
CATEGORIES = ("product", "sales", "case-studies", "marketing", "company")

# Where indexes are persisted (git-ignored — regenerated by `ingest`).
INDEX_DIR = REPO_DIR / ".index"
CHROMA_SUBDIR = "chroma"
BM25_FILENAME = "bm25.pkl"
CHUNKS_FILENAME = "chunks.jsonl"
MANIFEST_FILENAME = "manifest.json"
EMBEDDER_FILENAME = "embedder.npz"  # persisted fitted state (e.g. TF-IDF idf vector)
COLLECTION = "northstar"

# Chunking: split by markdown H2; fall back to a ~800-token window with 100 overlap.
MAX_TOKENS = 800
OVERLAP_TOKENS = 100
# Rough words<->tokens conversion (~1.3 tokens per whitespace word) so we can
# window in word-space without a tokenizer dependency / network download.
TOKENS_PER_WORD = 1.3

# Offline deterministic embedder dimensionality.
EMBED_DIM = 512
